name: ArgoCD CLI Action
description: Run ArgoCD CLI
inputs:
  server:
    required: True
  auth-token:
    required: True
runs:
  using: composite
  steps:
    - name: Download ArgoCD CLI
      shell: bash
      env:
        ARGOCD_VERSION: 3.0.6
        ARGOCD_SHA256: ae3257671dd0b7a787b21a70db43c3c869adec5dd520c90b419871a5ca1a8fc9 
      run: |
        curl -fsSL -o /usr/local/bin/argocd "https://github.com/argoproj/argo-cd/releases/download/v${ARGOCD_VERSION}/argocd-linux-amd64" && \
          echo "$ARGOCD_SHA256 /usr/local/bin/argocd" | sha256sum --check
        chmod +x /usr/local/bin/argocd
    - name: Execute ArgoCD CLI
      shell: bash
      env:
        ARGOCD_SERVER: ${{ inputs.server }}
        ARGOCD_AUTH_TOKEN: ${{ inputs.auth-token }}
      run: |
        argocd version
        argocd account get-user-info
        argocd app list

